<?xml version="1.0"?>
<package format="3">
  <name>iconom_competition</name>
  <version>0.1.0</version>
  <description>ROS 2 competition client for connecting to the mock referee server.</description>
  <maintainer email="devnull@example.com">iconom</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>px4_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
